Repository CHILLINGE/salenote-client, pull requests merged in 2022-05, with the labels that each got.

#5 styled component compiler 설정 추가
  site/next.config.js
Labels: documentation

#11 게임 검색 결과 컴포넌트 구현
  site/.storybook/preview-body.html
  site/.storybook/preview.js
  site/components/search/SearchResultItem.tsx
  site/components/search/SearchTextInput.tsx
  site/stories/SearchResultItem.stories.tsx
  site/stories/SearchText.stories.tsx
  site/styles/GlobalStyle.tsx
  site/styles/colors.ts
  site/styles/fonts.ts
Labels: :apple: 기능추가, :art: 디자인

#10 price info 컴포넌트 구현
  site/components/saleInfo/PriceInfo.tsx
  site/stories/PriceInfo.stories.tsx
  site/styles/colors.ts
Labels: :apple: 기능추가, :art: 디자인

#9 game info component 완료
  site/components/saleInfo/gameInfo/index.tsx
  site/components/saleInfo/gameInfo/topContents.tsx
  site/components/saleInfo/gameInfo/topImage.tsx
  site/package.json
  site/stories/GameInfo.stories.tsx
  site/stories/GameInfoTopContents.stories.tsx
  site/stories/GameInfoTopImage.stories.tsx
  site/styles/colors.ts
  yarn.lock
Labels: :apple: 기능추가, :art: 디자인

#14 steam store로 가는 버튼 추가
  site/components/gameInfo/GameDetails.stories.tsx
  site/components/gameInfo/GameDetails.tsx
  site/components/gameInfo/GameImage.stories.tsx
  site/components/gameInfo/GameImage.tsx
  site/components/gameInfo/GameInfo.stories.tsx
  site/components/gameInfo/GameInfo.tsx
  site/components/gameInfo/StoreLink.stories.tsx
  site/components/gameInfo/StoreLink.tsx
Labels: :apple: 기능추가, :art: 디자인

#12 avg discount rate comp 개발
  site/components/saleInfo/AvgDiscountRate.tsx
  site/gateway/gameInfo/mock.ts
  site/gateway/gameInfo/type.ts
  site/stories/AvgDiscountRate.stories.tsx
Labels: :apple: 기능추가, :art: 디자인, :fortune_cookie: dataFormat

#15 Feature seasonal discount
  site/components/gameInfo/GameInfo.stories.tsx
  site/components/gameInfo/GameInfo.tsx
  site/components/gameInfo/SeasonSaleProbabilityPhrase.stories.tsx
  site/components/gameInfo/SeasonSaleProbabilityPhrase.tsx
  site/components/seasonalSale/Figure.tsx
  site/components/seasonalSale/ParticipationProbability.stories.tsx
  site/components/seasonalSale/ParticipationProbability.tsx
  site/components/seasonalSale/SeasonSaleProbability.stories.tsx
  site/components/seasonalSale/SeasonSaleProbability.tsx
  site/styles/colors.ts
Labels: :apple: 기능추가, :art: 디자인, :fortune_cookie: dataFormat

#16 common accordion margin 조정
  site/components/common/CommonAccordion.tsx
Labels: :art: 디자인

#18 검색 컴포넌트 추가
  site/.storybook/preview.js
  site/components/search/Search.stories.tsx
  site/components/search/Search.tsx
  site/components/search/SearchResultItem.tsx
  site/components/search/SearchTextInput.tsx
  site/components/search/useSearch.ts
  site/gateway/factory.ts
  site/gateway/hook.tsx
  site/gateway/search/index.ts
  site/gateway/type.ts
  site/package.json
  site/pages/_app.tsx
  yarn.lock
Labels: :apple: 기능추가

#20 feat: Detail 페이지 레이아웃 추가
  site/components/layout/GameDetailLayout.tsx
  site/components/layout/footer/Footer.stories.tsx
  site/components/layout/footer/Footer.tsx
  site/components/layout/footer/FooterEntry.tsx
  site/pages/game/[gameid].tsx
  site/styles/fonts.ts
Labels: :apple: 기능추가
